function [params]=parameters()
    %% parameters
    
    % Rules:
	% 'name' field must be upper case
	% 'name' field must not exceed 16 letters
    % 'group' field should be short but is optional
    % 'default' field is NOT optional
	% 'Other fields ('min','max','decimal','increment','unit',description) may be optional but should be set to used in QGC
	
    params.dummy=struct('name', 'DUMMY',...
                        'group','OWN_PARAMS',...
                        'default', 1.00,...
                        'min', 0.001,...
                        'max', 10.000,...
                        'decimal',1,...
                        'increment',0.1,...
                        'unit', '',...
                        'description', 'just a dummy');
end