function defineBuses(messageFolder)
    % px4 bus definitions (.msg files)
    messageList=dir(fullfile(messageFolder, '*.msg'));
    
    for thisMessage=messageList'
        
        [bus, topics]=parseBus(fullfile(messageFolder, thisMessage.name));
        
        % Swarm usage: ignore timestamp inside simulink (except for vehicle_local_poosition and vehicle_local_position
%         if (~strcmp(topics{1,1},'vehicle_gps_position_bus') && ~strcmp(topics{1,1},'vehicle_local_position_bus'))
%             bus=bus(~strcmp({bus.name}, 'timestamp'));
%         end

        % Modified for Aerobotics with iFR Navigation Filter
        bus=bus(~strcmp({bus.name}, 'timestamp')); 

        theseBuses=cell(1, numel(topics));
        for j=1:numel(topics)
            theseBuses{j}={topics{j}, '', '', 'Auto', '-1', cell(1, numel(bus))};
            for k=1:numel(bus)
                if contains(bus(k).type, '64') % simulink does not support 64bit integral
                    theseBuses{j}{end}{k}={bus(k).name, bus(k).dimension, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''};
                else
                    theseBuses{j}{end}{k}={bus(k).name, bus(k).dimension, bus(k).type, -1, 'real', 'Sample', 'Fixed', [], [], '', ''};
                end
            end
        end
        Simulink.Bus.cellToObject(theseBuses)
    end
    
    % ifr internal bus definitions
    ifrInternalBuses={...
        {'ifr_imu', '', 'inertial measurements', 'Auto', '-1', {...
            {'time', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'rate', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'acceleration', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'ifr_opticalFlow', '', 'optical flow data', 'Auto', '-1', {...
            {'isValid', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'losRate', 2, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'ifr_sonar', '', 'sonar distance', 'Auto', '-1', {...
            {'isValid', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'distance', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'ifr_lidar', '', 'sonar distance', 'Auto', '-1', {...
            {'isValid', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'distance', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'ifr_smLidar', '', 'lidar parameters', 'Auto', '-1', {...
            {'valid'  , 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'enabled'  , 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        }},...
        {'ifr_gps', '', 'gps measurements', 'Auto', '-1', {...
            {'isValid', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'position', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'velocity', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'ifr_geodeticReference', '', 'geodetic reference data', 'Auto', '-1', {...
            {'earthMagneticField', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'gravity', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'refLlhRawToNed', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'refPosLlhRaw', 3, 'int32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
            {'refPosValid', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'ifr_baro', '', 'barometric height', 'Auto', '-1', {...
            {'isValid', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'height', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'ifr_mag', '', 'magnetometer measurement', 'Auto', '-1', {...
            {'isValid', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'magneticField', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'guidance_cmd', '', 'Results of guidance calculation', 'Auto', '-1', {...
            {'roll_lim', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'act_cmd', 6, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'rte_cmd', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'att_cmd', 5, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'trk_cmd', 3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }},...
        {'feedforward', '', 'feed forwards for trajectory tracking', 'Auto', '-1', {...
            {'phi_ffw', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'p_ffw', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'q_ffw', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'r_ffw', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'az_ffw', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'gamma_dot', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'alpha_dot', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'q_dot', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
        }}...,
        {'ifr_airdata', '', 'airdata measurement', 'Auto', '-1', {...
            {'isValid', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''},...
            {'V_a', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
            {'alpha', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
            {'beta', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}...
        }}...
    };
    Simulink.Bus.cellToObject(ifrInternalBuses)
end
